[package]
name = "cargo-pgo"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.1"

description = "Cargo subcommand for optimizing Rust binaries with PGO and BOLT."
repository = "https://github.com/kobzol/cargo-bolt"
authors = ["Jakub Beránek <berykubik@gmail.com>"]
keywords = [
    "pgo",
    "bolt",
    "cargo",
    "optimization",
    "feedback-directed-optimization",
    "profile-guided-optimization"
]
categories = ["development-tools::cargo-plugins"]

readme = "README.md"
license = "MIT"
include = [
    "src/*.rs",
    "Cargo.toml",
    "README.md"
]

[dependencies]
cargo = "0.60.0"
anyhow = "1"
which = "4.2"
clap = { version = "3.2", features = ["derive"] }
log = "0.4"
env_logger = "0.9.0"
colored = "2.0.0"
cargo_metadata = "0.15.0"
humansize = "1.1.1"
semver = "1.0.12"
tempfile = "3.3.0"
