## Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [ 1.80.0, stable, beta, nightly ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        run: |
          rustup toolchain install ${{ matrix.rust-version }}
          rustup default ${{ matrix.rust-version }}
          rustup component add clippy rustfmt llvm-tools-preview

      - name: Build
        run: cargo build --all --all-targets

      - name: Run tests
        run: cargo test

      - name: Lint
        run: cargo clippy --all -- -D warnings

      - name: Check Rust formatting
        run: cargo fmt --all -- --check

  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        run: |
          rustup toolchain install 1.80.0
          rustup default 1.80.0
          rustup component add clippy rustfmt llvm-tools-preview

      - name: Build
        run: cargo build --all --all-targets

      - name: Run tests
        run: cargo test
