## Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [ 1.78.0, stable, beta, nightly ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          components: clippy, rustfmt, llvm-tools-preview

      - name: Build
        run: cargo build --all --all-targets

      - name: Run tests
        run: cargo test

      - name: Lint
        run: clippy --all -- -D warnings

      - name: Check Rust formatting
        run: cargo fmt --all -- --check
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.78.0
          components: clippy, rustfmt, llvm-tools-preview

      - name: Build
        run: cargo build --all --all-targets

      - name: Run tests
        run: cargo test
